CREATE TABLE IF NOT EXISTS endpoint_hit (
    endpoint_hit_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app varchar,
    uri varchar,
    ip varchar,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT endpoint_hit_id_pk PRIMARY KEY (endpoint_hit_id)
);